<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		Country::create(['country_code'=>'AFG', 'country'=>'Afghanistan']);
		Country::create(['country_code'=>'ALA', 'country'=>'Aland Islands']);
		Country::create(['country_code'=>'ALB', 'country'=>'Albania']);
		Country::create(['country_code'=>'DZA', 'country'=>'Algeria']);
		Country::create(['country_code'=>'ASM', 'country'=>'American Samoa']);
		Country::create(['country_code'=>'AND', 'country'=>'Andorra']);
		Country::create(['country_code'=>'AGO', 'country'=>'Angola']);
		Country::create(['country_code'=>'AIA', 'country'=>'Anguilla']);
		Country::create(['country_code'=>'ATA', 'country'=>'Antarctica']);
		Country::create(['country_code'=>'ATG', 'country'=>'Antigua and Barbuda']);
		Country::create(['country_code'=>'ARG', 'country'=>'Argentina']);
		Country::create(['country_code'=>'ARM', 'country'=>'Armenia']);
		Country::create(['country_code'=>'ABW', 'country'=>'Aruba']);
		Country::create(['country_code'=>'AUS', 'country'=>'Australia']);
		Country::create(['country_code'=>'AUT', 'country'=>'Austria']);
		Country::create(['country_code'=>'AZE', 'country'=>'Azerbaijan']);
		Country::create(['country_code'=>'BHS', 'country'=>'Bahamas']);
		Country::create(['country_code'=>'BHR', 'country'=>'Bahrain']);
		Country::create(['country_code'=>'BGD', 'country'=>'Bangladesh']);
		Country::create(['country_code'=>'BRB', 'country'=>'Barbados']);
		Country::create(['country_code'=>'BLR', 'country'=>'Belarus']);
		Country::create(['country_code'=>'BEL', 'country'=>'Belgium']);
		Country::create(['country_code'=>'BLZ', 'country'=>'Belize']);
		Country::create(['country_code'=>'BEN', 'country'=>'Benin']);
		Country::create(['country_code'=>'BMU', 'country'=>'Bermuda']);
		Country::create(['country_code'=>'BTN', 'country'=>'Bhutan']);
		Country::create(['country_code'=>'BOL', 'country'=>'Bolivia']);
		Country::create(['country_code'=>'BIH', 'country'=>'Bosnia and Herzegovina']);
		Country::create(['country_code'=>'BWA', 'country'=>'Botswana']);
		Country::create(['country_code'=>'BVT', 'country'=>'Bouvet Island']);
		Country::create(['country_code'=>'BRA', 'country'=>'Brazil']);
		Country::create(['country_code'=>'VGB', 'country'=>'British Virgin Islands']);
		Country::create(['country_code'=>'IOT', 'country'=>'British Indian Ocean Territory']);
		Country::create(['country_code'=>'BRN', 'country'=>'Brunei Darussalam']);
		Country::create(['country_code'=>'BGR', 'country'=>'Bulgaria']);
		Country::create(['country_code'=>'BFA', 'country'=>'Burkina Faso']);
		Country::create(['country_code'=>'BDI', 'country'=>'Burundi']);
		Country::create(['country_code'=>'KHM', 'country'=>'Cambodia']);
		Country::create(['country_code'=>'CMR', 'country'=>'Cameroon']);
		Country::create(['country_code'=>'CAN', 'country'=>'Canada']);
		Country::create(['country_code'=>'CPV', 'country'=>'Cape Verde']);
		Country::create(['country_code'=>'CYM', 'country'=>'Cayman Islands']);
		Country::create(['country_code'=>'CAF', 'country'=>'Central African Republic']);
		Country::create(['country_code'=>'TCD', 'country'=>'Chad']);
		Country::create(['country_code'=>'CHL', 'country'=>'Chile']);
		Country::create(['country_code'=>'CHN', 'country'=>'China']);
		Country::create(['country_code'=>'HKG', 'country'=>'Hong Kong, SAR China']);
		Country::create(['country_code'=>'MAC', 'country'=>'Macao, SAR China']);
		Country::create(['country_code'=>'CXR', 'country'=>'Christmas Island']);
		Country::create(['country_code'=>'CCK', 'country'=>'Cocos (Keeling) Islands']);
		Country::create(['country_code'=>'COL', 'country'=>'Colombia']);
		Country::create(['country_code'=>'COM', 'country'=>'Comoros']);
		Country::create(['country_code'=>'COG', 'country'=>'Congo (Brazzaville)']);
		Country::create(['country_code'=>'COD', 'country'=>'Congo, (Kinshasa)']);
		Country::create(['country_code'=>'COK', 'country'=>'Cook Islands']);
		Country::create(['country_code'=>'CRI', 'country'=>'Costa Rica']);
		Country::create(['country_code'=>'CIV', 'country'=>'Côte d Ivoire']);
		Country::create(['country_code'=>'HRV', 'country'=>'Croatia']);
		Country::create(['country_code'=>'CUB', 'country'=>'Cuba']);
		Country::create(['country_code'=>'CYP', 'country'=>'Cyprus']);
		Country::create(['country_code'=>'CZE', 'country'=>'Czech Republic']);
		Country::create(['country_code'=>'DNK', 'country'=>'Denmark']);
		Country::create(['country_code'=>'DJI', 'country'=>'Djibouti']);
		Country::create(['country_code'=>'DMA', 'country'=>'Dominica']);
		Country::create(['country_code'=>'DOM', 'country'=>'Dominican Republic']);
		Country::create(['country_code'=>'ECU', 'country'=>'Ecuador']);
		Country::create(['country_code'=>'EGY', 'country'=>'Egypt']);
		Country::create(['country_code'=>'SLV', 'country'=>'El Salvador']);
		Country::create(['country_code'=>'GNQ', 'country'=>'Equatorial Guinea']);
		Country::create(['country_code'=>'ERI', 'country'=>'Eritrea']);
		Country::create(['country_code'=>'EST', 'country'=>'Estonia']);
		Country::create(['country_code'=>'ETH', 'country'=>'Ethiopia']);
		Country::create(['country_code'=>'FLK', 'country'=>'Falkland Islands (Malvinas)']);
		Country::create(['country_code'=>'FRO', 'country'=>'Faroe Islands']);
		Country::create(['country_code'=>'FJI', 'country'=>'Fiji']);
		Country::create(['country_code'=>'FIN', 'country'=>'Finland']);
		Country::create(['country_code'=>'FRA', 'country'=>'France']);
		Country::create(['country_code'=>'GUF', 'country'=>'French Guiana']);
		Country::create(['country_code'=>'PYF', 'country'=>'French Polynesia']);
		Country::create(['country_code'=>'ATF', 'country'=>'French Southern Territories']);
		Country::create(['country_code'=>'GAB', 'country'=>'Gabon']);
		Country::create(['country_code'=>'GMB', 'country'=>'Gambia']);
		Country::create(['country_code'=>'GEO', 'country'=>'Georgia']);
		Country::create(['country_code'=>'DEU', 'country'=>'Germany']);
		Country::create(['country_code'=>'GHA', 'country'=>'Ghana']);
		Country::create(['country_code'=>'GIB', 'country'=>'Gibraltar']);
		Country::create(['country_code'=>'GRC', 'country'=>'Greece']);
		Country::create(['country_code'=>'GRL', 'country'=>'Greenland']);
		Country::create(['country_code'=>'GRD', 'country'=>'Grenada']);
		Country::create(['country_code'=>'GLP', 'country'=>'Guadeloupe']);
		Country::create(['country_code'=>'GUM', 'country'=>'Guam']);
		Country::create(['country_code'=>'GTM', 'country'=>'Guatemala']);
		Country::create(['country_code'=>'GGY', 'country'=>'Guernsey']);
		Country::create(['country_code'=>'GIN', 'country'=>'Guinea']);
		Country::create(['country_code'=>'GNB', 'country'=>'Guinea-Bissau']);
		Country::create(['country_code'=>'GUY', 'country'=>'Guyana']);
		Country::create(['country_code'=>'HTI', 'country'=>'Haiti']);
		Country::create(['country_code'=>'HMD', 'country'=>'Heard and Mcdonald Islands']);
		Country::create(['country_code'=>'VAT', 'country'=>'Holy See (Vatican City State)']);
		Country::create(['country_code'=>'HND', 'country'=>'Honduras']);
		Country::create(['country_code'=>'HUN', 'country'=>'Hungary']);
		Country::create(['country_code'=>'ISL', 'country'=>'Iceland']);
		Country::create(['country_code'=>'IND', 'country'=>'India']);
		Country::create(['country_code'=>'IDN', 'country'=>'Indonesia']);
		Country::create(['country_code'=>'IRN', 'country'=>'Iran, Islamic Republic of']);
		Country::create(['country_code'=>'IRQ', 'country'=>'Iraq']);
		Country::create(['country_code'=>'IRL', 'country'=>'Ireland']);
		Country::create(['country_code'=>'IMN', 'country'=>'Isle of Man']);
		Country::create(['country_code'=>'ISR', 'country'=>'Israel']);
		Country::create(['country_code'=>'ITA', 'country'=>'Italy']);
		Country::create(['country_code'=>'JAM', 'country'=>'Jamaica']);
		Country::create(['country_code'=>'JPN', 'country'=>'Japan']);
		Country::create(['country_code'=>'JEY', 'country'=>'Jersey']);
		Country::create(['country_code'=>'JOR', 'country'=>'Jordan']);
		Country::create(['country_code'=>'KAZ', 'country'=>'Kazakhstan']);
		Country::create(['country_code'=>'KEN', 'country'=>'Kenya']);
		Country::create(['country_code'=>'KIR', 'country'=>'Kiribati']);
		Country::create(['country_code'=>'PRK', 'country'=>'Korea (North)']);
		Country::create(['country_code'=>'KOR', 'country'=>'Korea (South)']);
		Country::create(['country_code'=>'KWT', 'country'=>'Kuwait']);
		Country::create(['country_code'=>'KGZ', 'country'=>'Kyrgyzstan']);
		Country::create(['country_code'=>'LAO', 'country'=>'Lao PDR']);
		Country::create(['country_code'=>'LVA', 'country'=>'Latvia']);
		Country::create(['country_code'=>'LBN', 'country'=>'Lebanon']);
		Country::create(['country_code'=>'LSO', 'country'=>'Lesotho']);
		Country::create(['country_code'=>'LBR', 'country'=>'Liberia']);
		Country::create(['country_code'=>'LBY', 'country'=>'Libya']);
		Country::create(['country_code'=>'LIE', 'country'=>'Liechtenstein']);
		Country::create(['country_code'=>'LTU', 'country'=>'Lithuania']);
		Country::create(['country_code'=>'LUX', 'country'=>'Luxembourg']);
		Country::create(['country_code'=>'MKD', 'country'=>'Macedonia, Republic of']);
		Country::create(['country_code'=>'MDG', 'country'=>'Madagascar']);
		Country::create(['country_code'=>'MWI', 'country'=>'Malawi']);
		Country::create(['country_code'=>'MYS', 'country'=>'Malaysia']);
		Country::create(['country_code'=>'MDV', 'country'=>'Maldives']);
		Country::create(['country_code'=>'MLI', 'country'=>'Mali']);
		Country::create(['country_code'=>'MLT', 'country'=>'Malta']);
		Country::create(['country_code'=>'MHL', 'country'=>'Marshall Islands']);
		Country::create(['country_code'=>'MTQ', 'country'=>'Martinique']);
		Country::create(['country_code'=>'MRT', 'country'=>'Mauritania']);
		Country::create(['country_code'=>'MUS', 'country'=>'Mauritius']);
		Country::create(['country_code'=>'MYT', 'country'=>'Mayotte']);
		Country::create(['country_code'=>'MEX', 'country'=>'Mexico']);
		Country::create(['country_code'=>'FSM', 'country'=>'Micronesia, Federated States of']);
		Country::create(['country_code'=>'MDA', 'country'=>'Moldova']);
		Country::create(['country_code'=>'MCO', 'country'=>'Monaco']);
		Country::create(['country_code'=>'MNG', 'country'=>'Mongolia']);
		Country::create(['country_code'=>'MNE', 'country'=>'Montenegro']);
		Country::create(['country_code'=>'MSR', 'country'=>'Montserrat']);
		Country::create(['country_code'=>'MAR', 'country'=>'Morocco']);
		Country::create(['country_code'=>'MOZ', 'country'=>'Mozambique']);
		Country::create(['country_code'=>'MMR', 'country'=>'Myanmar']);
		Country::create(['country_code'=>'NAM', 'country'=>'Namibia']);
		Country::create(['country_code'=>'NRU', 'country'=>'Nauru']);
		Country::create(['country_code'=>'NPL', 'country'=>'Nepal']);
		Country::create(['country_code'=>'NLD', 'country'=>'Netherlands']);
		Country::create(['country_code'=>'ANT', 'country'=>'Netherlands Antilles']);
		Country::create(['country_code'=>'NCL', 'country'=>'New Caledonia']);
		Country::create(['country_code'=>'NZL', 'country'=>'New Zealand']);
		Country::create(['country_code'=>'NIC', 'country'=>'Nicaragua']);
		Country::create(['country_code'=>'NER', 'country'=>'Niger']);
		Country::create(['country_code'=>'NGA', 'country'=>'Nigeria']);
		Country::create(['country_code'=>'NIU', 'country'=>'Niue']);
		Country::create(['country_code'=>'NFK', 'country'=>'Norfolk Island']);
		Country::create(['country_code'=>'MNP', 'country'=>'Northern Mariana Islands']);
		Country::create(['country_code'=>'NOR', 'country'=>'Norway']);
		Country::create(['country_code'=>'OMN', 'country'=>'Oman']);
		Country::create(['country_code'=>'PAK', 'country'=>'Pakistan']);
		Country::create(['country_code'=>'PLW', 'country'=>'Palau']);
		Country::create(['country_code'=>'PSE', 'country'=>'Palestinian Territory']);
		Country::create(['country_code'=>'PAN', 'country'=>'Panama']);
		Country::create(['country_code'=>'PNG', 'country'=>'Papua New Guinea']);
		Country::create(['country_code'=>'PRY', 'country'=>'Paraguay']);
		Country::create(['country_code'=>'PER', 'country'=>'Peru']);
		Country::create(['country_code'=>'PHL', 'country'=>'Philippines']);
		Country::create(['country_code'=>'PCN', 'country'=>'Pitcairn']);
		Country::create(['country_code'=>'POL', 'country'=>'Poland']);
		Country::create(['country_code'=>'PRT', 'country'=>'Portugal']);
		Country::create(['country_code'=>'PRI', 'country'=>'Puerto Rico']);
		Country::create(['country_code'=>'QAT', 'country'=>'Qatar']);
		Country::create(['country_code'=>'REU', 'country'=>'Réunion']);
		Country::create(['country_code'=>'ROU', 'country'=>'Romania']);
		Country::create(['country_code'=>'RUS', 'country'=>'Russian Federation']);
		Country::create(['country_code'=>'RWA', 'country'=>'Rwanda']);
		Country::create(['country_code'=>'BLM', 'country'=>'Saint-Barthélemy']);
		Country::create(['country_code'=>'SHN', 'country'=>'Saint Helena']);
		Country::create(['country_code'=>'KNA', 'country'=>'Saint Kitts and Nevis']);
		Country::create(['country_code'=>'LCA', 'country'=>'Saint Lucia']);
		Country::create(['country_code'=>'MAF', 'country'=>'Saint-Martin (French part)']);
		Country::create(['country_code'=>'SPM', 'country'=>'Saint Pierre and Miquelon']);
		Country::create(['country_code'=>'VCT', 'country'=>'Saint Vincent and Grenadines']);
		Country::create(['country_code'=>'WSM', 'country'=>'Samoa']);
		Country::create(['country_code'=>'SMR', 'country'=>'San Marino']);
		Country::create(['country_code'=>'STP', 'country'=>'Sao Tome and Principe']);
		Country::create(['country_code'=>'SAU', 'country'=>'Saudi Arabia']);
		Country::create(['country_code'=>'SEN', 'country'=>'Senegal']);
		Country::create(['country_code'=>'SRB', 'country'=>'Serbia']);
		Country::create(['country_code'=>'SYC', 'country'=>'Seychelles']);
		Country::create(['country_code'=>'SLE', 'country'=>'Sierra Leone']);
		Country::create(['country_code'=>'SGP', 'country'=>'Singapore']);
		Country::create(['country_code'=>'SVK', 'country'=>'Slovakia']);
		Country::create(['country_code'=>'SVN', 'country'=>'Slovenia']);
		Country::create(['country_code'=>'SLB', 'country'=>'Solomon Islands']);
		Country::create(['country_code'=>'SOM', 'country'=>'Somalia']);
		Country::create(['country_code'=>'ZAF', 'country'=>'South Africa']);
		Country::create(['country_code'=>'SGS', 'country'=>'South Georgia and the South Sandwich Islands']);
		Country::create(['country_code'=>'SSD', 'country'=>'South Sudan']);
		Country::create(['country_code'=>'ESP', 'country'=>'Spain']);
		Country::create(['country_code'=>'LKA', 'country'=>'Sri Lanka']);
		Country::create(['country_code'=>'SDN', 'country'=>'Sudan']);
		Country::create(['country_code'=>'SUR', 'country'=>'Suriname']);
		Country::create(['country_code'=>'SJM', 'country'=>'Svalbard and Jan Mayen Islands']);
		Country::create(['country_code'=>'SWZ', 'country'=>'Swaziland']);
		Country::create(['country_code'=>'SWE', 'country'=>'Sweden']);
		Country::create(['country_code'=>'CHE', 'country'=>'Switzerland']);
		Country::create(['country_code'=>'SYR', 'country'=>'Syrian Arab Republic (Syria)']);
		Country::create(['country_code'=>'TWN', 'country'=>'Taiwan, Republic of China']);
		Country::create(['country_code'=>'TJK', 'country'=>'Tajikistan']);
		Country::create(['country_code'=>'TZA', 'country'=>'Tanzania, United Republic of']);
		Country::create(['country_code'=>'THA', 'country'=>'Thailand']);
		Country::create(['country_code'=>'TLS', 'country'=>'Timor-Leste']);
		Country::create(['country_code'=>'TGO', 'country'=>'Togo']);
		Country::create(['country_code'=>'TKL', 'country'=>'Tokelau']);
		Country::create(['country_code'=>'TON', 'country'=>'Tonga']);
		Country::create(['country_code'=>'TTO', 'country'=>'Trinidad and Tobago']);
		Country::create(['country_code'=>'TUN', 'country'=>'Tunisia']);
		Country::create(['country_code'=>'TUR', 'country'=>'Turkey']);
		Country::create(['country_code'=>'TKM', 'country'=>'Turkmenistan']);
		Country::create(['country_code'=>'TCA', 'country'=>'Turks and Caicos Islands']);
		Country::create(['country_code'=>'TUV', 'country'=>'Tuvalu']);
		Country::create(['country_code'=>'UGA', 'country'=>'Uganda']);
		Country::create(['country_code'=>'UKR', 'country'=>'Ukraine']);
		Country::create(['country_code'=>'ARE', 'country'=>'United Arab Emirates']);
		Country::create(['country_code'=>'GBR', 'country'=>'United Kingdom']);
		Country::create(['country_code'=>'USA', 'country'=>'United States of America']);
		Country::create(['country_code'=>'UMI', 'country'=>'US Minor Outlying Islands']);
		Country::create(['country_code'=>'URY', 'country'=>'Uruguay']);
		Country::create(['country_code'=>'UZB', 'country'=>'Uzbekistan']);
		Country::create(['country_code'=>'VUT', 'country'=>'Vanuatu']);
		Country::create(['country_code'=>'VEN', 'country'=>'Venezuela (Bolivarian Republic)']);
		Country::create(['country_code'=>'VNM', 'country'=>'Viet Nam']);
		Country::create(['country_code'=>'VIR', 'country'=>'Virgin Islands, US']);
		Country::create(['country_code'=>'WLF', 'country'=>'Wallis and Futuna Islands']);
		Country::create(['country_code'=>'ESH', 'country'=>'Western Sahara']);
		Country::create(['country_code'=>'YEM', 'country'=>'Yemen']);
		Country::create(['country_code'=>'ZMB', 'country'=>'Zambia']);
		Country::create(['country_code'=>'ZWE', 'country'=>'Zimbabwe']);
    }
}
