<?php

use Illuminate\Database\Seeder;
use App\Currency;

class CurrencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Currency::firstOrCreate(['currency'=>'USD', 'currency_description'=>'US Dollar']);
		Currency::firstOrCreate(['currency'=>'EUR', 'currency_description'=>'Euro']);
		Currency::firstOrCreate(['currency'=>'GBP', 'currency_description'=>'British Pound']);
		Currency::firstOrCreate(['currency'=>'INR', 'currency_description'=>'Indian Rupee']);
		Currency::firstOrCreate(['currency'=>'AUD', 'currency_description'=>'Australian Dollar']);
		Currency::firstOrCreate(['currency'=>'CAD', 'currency_description'=>'Canadian Dollar']);
		Currency::firstOrCreate(['currency'=>'SGD', 'currency_description'=>'Singapore Dollar']);
		Currency::firstOrCreate(['currency'=>'CHF', 'currency_description'=>'Swiss Franc']);
		Currency::firstOrCreate(['currency'=>'MYR', 'currency_description'=>'Malaysian Ringgit']);
		Currency::firstOrCreate(['currency'=>'JPY', 'currency_description'=>'Japanese Yen']);
		Currency::firstOrCreate(['currency'=>'CNY', 'currency_description'=>'Chinese Yuan Renminbi']);
		Currency::firstOrCreate(['currency'=>'NZD', 'currency_description'=>'New Zealand Dollar']);
		Currency::firstOrCreate(['currency'=>'THB', 'currency_description'=>'Thai Baht']);
		Currency::firstOrCreate(['currency'=>'HUF', 'currency_description'=>'Hungarian Forint']);
		Currency::firstOrCreate(['currency'=>'AED', 'currency_description'=>'Emirati Dirham']);
		Currency::firstOrCreate(['currency'=>'HKD', 'currency_description'=>'Hong Kong Dollar']);
		Currency::firstOrCreate(['currency'=>'MXN', 'currency_description'=>'Mexican Peso']);
		Currency::firstOrCreate(['currency'=>'ZAR', 'currency_description'=>'South African Rand']);
		Currency::firstOrCreate(['currency'=>'PHP', 'currency_description'=>'Philippine Peso']);
		Currency::firstOrCreate(['currency'=>'SEK', 'currency_description'=>'Swedish Krona']);
		Currency::firstOrCreate(['currency'=>'IDR', 'currency_description'=>'Indonesian Rupiah']);
		Currency::firstOrCreate(['currency'=>'SAR', 'currency_description'=>'Saudi Arabian Riyal']);
		Currency::firstOrCreate(['currency'=>'BRL', 'currency_description'=>'Brazilian Real']);
		Currency::firstOrCreate(['currency'=>'TRY', 'currency_description'=>'Turkish Lira']);
		Currency::firstOrCreate(['currency'=>'KES', 'currency_description'=>'Kenyan Shilling']);
		Currency::firstOrCreate(['currency'=>'KRW', 'currency_description'=>'South Korean Won']);
		Currency::firstOrCreate(['currency'=>'EGP', 'currency_description'=>'Egyptian Pound']);
		Currency::firstOrCreate(['currency'=>'IQD', 'currency_description'=>'Iraqi Dinar']);
		Currency::firstOrCreate(['currency'=>'NOK', 'currency_description'=>'Norwegian Krone']);
		Currency::firstOrCreate(['currency'=>'KWD', 'currency_description'=>'Kuwaiti Dinar']);
		Currency::firstOrCreate(['currency'=>'RUB', 'currency_description'=>'Russian Ruble']);
		Currency::firstOrCreate(['currency'=>'DKK', 'currency_description'=>'Danish Krone']);
		Currency::firstOrCreate(['currency'=>'PKR', 'currency_description'=>'Pakistani Rupee']);
		Currency::firstOrCreate(['currency'=>'ILS', 'currency_description'=>'Israeli Shekel']);
		Currency::firstOrCreate(['currency'=>'PLN', 'currency_description'=>'Polish Zloty']);
		Currency::firstOrCreate(['currency'=>'QAR', 'currency_description'=>'Qatari Riyal']);
		Currency::firstOrCreate(['currency'=>'XAU', 'currency_description'=>'Gold Ounce']);
		Currency::firstOrCreate(['currency'=>'OMR', 'currency_description'=>'Omani Rial']);
		Currency::firstOrCreate(['currency'=>'COP', 'currency_description'=>'Colombian Peso']);
		Currency::firstOrCreate(['currency'=>'CLP', 'currency_description'=>'Chilean Peso']);
		Currency::firstOrCreate(['currency'=>'TWD', 'currency_description'=>'Taiwan New Dollar']);
		Currency::firstOrCreate(['currency'=>'ARS', 'currency_description'=>'Argentine Peso']);
		Currency::firstOrCreate(['currency'=>'CZK', 'currency_description'=>'Czech Koruna']);
		Currency::firstOrCreate(['currency'=>'VND', 'currency_description'=>'Vietnamese Dong']);
		Currency::firstOrCreate(['currency'=>'MAD', 'currency_description'=>'Moroccan Dirham']);
		Currency::firstOrCreate(['currency'=>'JOD', 'currency_description'=>'Jordanian Dinar']);
		Currency::firstOrCreate(['currency'=>'BHD', 'currency_description'=>'Bahraini Dinar']);
		Currency::firstOrCreate(['currency'=>'XOF', 'currency_description'=>'CFA Franc']);
		Currency::firstOrCreate(['currency'=>'LKR', 'currency_description'=>'Sri Lankan Rupee']);
		Currency::firstOrCreate(['currency'=>'UAH', 'currency_description'=>'Ukrainian Hryvnia']);
		Currency::firstOrCreate(['currency'=>'NGN', 'currency_description'=>'Nigerian Naira']);
		Currency::firstOrCreate(['currency'=>'TND', 'currency_description'=>'Tunisian Dinar']);
		Currency::firstOrCreate(['currency'=>'UGX', 'currency_description'=>'Ugandan Shilling']);
		Currency::firstOrCreate(['currency'=>'RON', 'currency_description'=>'Romanian Leu']);
		Currency::firstOrCreate(['currency'=>'BDT', 'currency_description'=>'Bangladeshi Taka']);
		Currency::firstOrCreate(['currency'=>'PEN', 'currency_description'=>'Peruvian Sol']);
		Currency::firstOrCreate(['currency'=>'GEL', 'currency_description'=>'Georgian Lari']);
		Currency::firstOrCreate(['currency'=>'XAF', 'currency_description'=>'Central African CFA Franc BEAC']);
		Currency::firstOrCreate(['currency'=>'FJD', 'currency_description'=>'Fijian Dollar']);
		Currency::firstOrCreate(['currency'=>'VEF', 'currency_description'=>'Venezuelan Bolívar']);
		Currency::firstOrCreate(['currency'=>'BYN', 'currency_description'=>'Belarusian Ruble']);
		Currency::firstOrCreate(['currency'=>'HRK', 'currency_description'=>'Croatian Kuna']);
		Currency::firstOrCreate(['currency'=>'UZS', 'currency_description'=>'Uzbekistani Som']);
		Currency::firstOrCreate(['currency'=>'BGN', 'currency_description'=>'Bulgarian Lev']);
		Currency::firstOrCreate(['currency'=>'DZD', 'currency_description'=>'Algerian Dinar']);
		Currency::firstOrCreate(['currency'=>'IRR', 'currency_description'=>'Iranian Rial']);
		Currency::firstOrCreate(['currency'=>'DOP', 'currency_description'=>'Dominican Peso']);
		Currency::firstOrCreate(['currency'=>'ISK', 'currency_description'=>'Icelandic Krona']);
		Currency::firstOrCreate(['currency'=>'XAG', 'currency_description'=>'Silver Ounce']);
		Currency::firstOrCreate(['currency'=>'CRC', 'currency_description'=>'Costa Rican Colon']);
		Currency::firstOrCreate(['currency'=>'SYP', 'currency_description'=>'Syrian Pound']);
		Currency::firstOrCreate(['currency'=>'LYD', 'currency_description'=>'Libyan Dinar']);
		Currency::firstOrCreate(['currency'=>'JMD', 'currency_description'=>'Jamaican Dollar']);
		Currency::firstOrCreate(['currency'=>'MUR', 'currency_description'=>'Mauritian Rupee']);
		Currency::firstOrCreate(['currency'=>'GHS', 'currency_description'=>'Ghanaian Cedi']);
		Currency::firstOrCreate(['currency'=>'AOA', 'currency_description'=>'Angolan Kwanza']);
		Currency::firstOrCreate(['currency'=>'UYU', 'currency_description'=>'Uruguayan Peso']);
		Currency::firstOrCreate(['currency'=>'AFN', 'currency_description'=>'Afghan Afghani']);
		Currency::firstOrCreate(['currency'=>'LBP', 'currency_description'=>'Lebanese Pound']);
		Currency::firstOrCreate(['currency'=>'XPF', 'currency_description'=>'CFP Franc']);
		Currency::firstOrCreate(['currency'=>'TTD', 'currency_description'=>'Trinidadian Dollar']);
		Currency::firstOrCreate(['currency'=>'TZS', 'currency_description'=>'Tanzanian Shilling']);
		Currency::firstOrCreate(['currency'=>'ALL', 'currency_description'=>'Albanian Lek']);
		Currency::firstOrCreate(['currency'=>'XCD', 'currency_description'=>'East Caribbean Dollar']);
		Currency::firstOrCreate(['currency'=>'GTQ', 'currency_description'=>'Guatemalan Quetzal']);
		Currency::firstOrCreate(['currency'=>'NPR', 'currency_description'=>'Nepalese Rupee']);
		Currency::firstOrCreate(['currency'=>'BOB', 'currency_description'=>'Bolivian Bolíviano']);
		Currency::firstOrCreate(['currency'=>'ZWD', 'currency_description'=>'Zimbabwean Dollar']);
		Currency::firstOrCreate(['currency'=>'BBD', 'currency_description'=>'Barbadian or Bajan Dollar']);
		Currency::firstOrCreate(['currency'=>'CUC', 'currency_description'=>'Cuban Convertible Peso']);
		Currency::firstOrCreate(['currency'=>'LAK', 'currency_description'=>'Lao Kip']);
		Currency::firstOrCreate(['currency'=>'BND', 'currency_description'=>'Bruneian Dollar']);
		Currency::firstOrCreate(['currency'=>'BWP', 'currency_description'=>'Botswana Pula']);
		Currency::firstOrCreate(['currency'=>'HNL', 'currency_description'=>'Honduran Lempira']);
		Currency::firstOrCreate(['currency'=>'PYG', 'currency_description'=>'Paraguayan Guarani']);
		Currency::firstOrCreate(['currency'=>'ETB', 'currency_description'=>'Ethiopian Birr']);
		Currency::firstOrCreate(['currency'=>'NAD', 'currency_description'=>'Namibian Dollar']);
		Currency::firstOrCreate(['currency'=>'PGK', 'currency_description'=>'Papua New Guinean Kina']);
		Currency::firstOrCreate(['currency'=>'SDG', 'currency_description'=>'Sudanese Pound']);
		Currency::firstOrCreate(['currency'=>'MOP', 'currency_description'=>'Macau Pataca']);
		Currency::firstOrCreate(['currency'=>'NIO', 'currency_description'=>'Nicaraguan Cordoba']);
		Currency::firstOrCreate(['currency'=>'BMD', 'currency_description'=>'Bermudian Dollar']);
		Currency::firstOrCreate(['currency'=>'KZT', 'currency_description'=>'Kazakhstani Tenge']);
		Currency::firstOrCreate(['currency'=>'PAB', 'currency_description'=>'Panamanian Balboa']);
		Currency::firstOrCreate(['currency'=>'BAM', 'currency_description'=>'Bosnian Convertible Marka']);
		Currency::firstOrCreate(['currency'=>'GYD', 'currency_description'=>'Guyanese Dollar']);
		Currency::firstOrCreate(['currency'=>'YER', 'currency_description'=>'Yemeni Rial']);
		Currency::firstOrCreate(['currency'=>'MGA', 'currency_description'=>'Malagasy Ariary']);
		Currency::firstOrCreate(['currency'=>'KYD', 'currency_description'=>'Caymanian Dollar']);
		Currency::firstOrCreate(['currency'=>'MZN', 'currency_description'=>'Mozambican Metical']);
		Currency::firstOrCreate(['currency'=>'RSD', 'currency_description'=>'Serbian Dinar']);
		Currency::firstOrCreate(['currency'=>'SCR', 'currency_description'=>'Seychellois Rupee']);
		Currency::firstOrCreate(['currency'=>'AMD', 'currency_description'=>'Armenian Dram']);
		Currency::firstOrCreate(['currency'=>'SBD', 'currency_description'=>'Solomon Islander Dollar']);
		Currency::firstOrCreate(['currency'=>'AZN', 'currency_description'=>'Azerbaijan Manat']);
		Currency::firstOrCreate(['currency'=>'SLL', 'currency_description'=>'Sierra Leonean Leone']);
		Currency::firstOrCreate(['currency'=>'TOP', 'currency_description'=>'Tongan Pa anga']);
		Currency::firstOrCreate(['currency'=>'BZD', 'currency_description'=>'Belizean Dollar']);
		Currency::firstOrCreate(['currency'=>'MWK', 'currency_description'=>'Malawian Kwacha']);
		Currency::firstOrCreate(['currency'=>'GMD', 'currency_description'=>'Gambian Dalasi']);
		Currency::firstOrCreate(['currency'=>'BIF', 'currency_description'=>'Burundian Franc']);
		Currency::firstOrCreate(['currency'=>'SOS', 'currency_description'=>'Somali Shilling']);
		Currency::firstOrCreate(['currency'=>'HTG', 'currency_description'=>'Haitian Gourde']);
		Currency::firstOrCreate(['currency'=>'GNF', 'currency_description'=>'Guinean Franc']);
		Currency::firstOrCreate(['currency'=>'MVR', 'currency_description'=>'Maldivian Rufiyaa']);
		Currency::firstOrCreate(['currency'=>'MNT', 'currency_description'=>'Mongolian Tughrik']);
		Currency::firstOrCreate(['currency'=>'CDF', 'currency_description'=>'Congolese Franc']);
		Currency::firstOrCreate(['currency'=>'STD', 'currency_description'=>'Sao Tomean Dobra']);
		Currency::firstOrCreate(['currency'=>'TJS', 'currency_description'=>'Tajikistani Somoni']);
		Currency::firstOrCreate(['currency'=>'KPW', 'currency_description'=>'North Korean Won']);
		Currency::firstOrCreate(['currency'=>'MMK', 'currency_description'=>'Burmese Kyat']);
		Currency::firstOrCreate(['currency'=>'LSL', 'currency_description'=>'Basotho Loti']);
		Currency::firstOrCreate(['currency'=>'LRD', 'currency_description'=>'Liberian Dollar']);
		Currency::firstOrCreate(['currency'=>'KGS', 'currency_description'=>'Kyrgyzstani Som']);
		Currency::firstOrCreate(['currency'=>'GIP', 'currency_description'=>'Gibraltar Pound']);
		Currency::firstOrCreate(['currency'=>'XPT', 'currency_description'=>'Platinum Ounce']);
		Currency::firstOrCreate(['currency'=>'MDL', 'currency_description'=>'Moldovan Leu']);
		Currency::firstOrCreate(['currency'=>'CUP', 'currency_description'=>'Cuban Peso']);
		Currency::firstOrCreate(['currency'=>'KHR', 'currency_description'=>'Cambodian Riel']);
		Currency::firstOrCreate(['currency'=>'MKD', 'currency_description'=>'Macedonian Denar']);
		Currency::firstOrCreate(['currency'=>'VUV', 'currency_description'=>'Ni-Vanuatu Vatu']);
		Currency::firstOrCreate(['currency'=>'MRO', 'currency_description'=>'Mauritanian Ouguiya']);
		Currency::firstOrCreate(['currency'=>'ANG', 'currency_description'=>'Dutch Guilder']);
		Currency::firstOrCreate(['currency'=>'SZL', 'currency_description'=>'Swazi Lilangeni']);
		Currency::firstOrCreate(['currency'=>'CVE', 'currency_description'=>'Cape Verdean Escudo']);
		Currency::firstOrCreate(['currency'=>'SRD', 'currency_description'=>'Surinamese Dollar']);
		Currency::firstOrCreate(['currency'=>'XPD', 'currency_description'=>'Palladium Ounce']);
		Currency::firstOrCreate(['currency'=>'SVC', 'currency_description'=>'Salvadoran Colon']);
		Currency::firstOrCreate(['currency'=>'BSD', 'currency_description'=>'Bahamian Dollar']);
		Currency::firstOrCreate(['currency'=>'XDR', 'currency_description'=>'IMF Special Drawing Rights']);
		Currency::firstOrCreate(['currency'=>'RWF', 'currency_description'=>'Rwandan Franc']);
		Currency::firstOrCreate(['currency'=>'AWG', 'currency_description'=>'Aruban or Dutch Guilder']);
		Currency::firstOrCreate(['currency'=>'DJF', 'currency_description'=>'Djiboutian Franc']);
		Currency::firstOrCreate(['currency'=>'BTN', 'currency_description'=>'Bhutanese Ngultrum']);
		Currency::firstOrCreate(['currency'=>'KMF', 'currency_description'=>'Comorian Franc']);
		Currency::firstOrCreate(['currency'=>'WST', 'currency_description'=>'Samoan Tala']);
		Currency::firstOrCreate(['currency'=>'SPL', 'currency_description'=>'Seborgan Luigino']);
		Currency::firstOrCreate(['currency'=>'ERN', 'currency_description'=>'Eritrean Nakfa']);
		Currency::firstOrCreate(['currency'=>'FKP', 'currency_description'=>'Falkland Island Pound']);
		Currency::firstOrCreate(['currency'=>'SHP', 'currency_description'=>'Saint Helenian Pound']);
		Currency::firstOrCreate(['currency'=>'JEP', 'currency_description'=>'Jersey Pound']);
		Currency::firstOrCreate(['currency'=>'TMT', 'currency_description'=>'Turkmenistani Manat']);
		Currency::firstOrCreate(['currency'=>'TVD', 'currency_description'=>'Tuvaluan Dollar']);
		Currency::firstOrCreate(['currency'=>'IMP', 'currency_description'=>'Isle of Man Pound']);
		Currency::firstOrCreate(['currency'=>'GGP', 'currency_description'=>'Guernsey Pound']);
		Currency::firstOrCreate(['currency'=>'ZMW', 'currency_description'=>'Zambian Kwacha']);
    }
}
